gatling-maven-plugin/src/main/java/io/gatling/mojo/GatlingMojo.java
Gatling Maven plugin fails to startup if there's URL special char like '%' in the path with `ClassNotFoundException`:
```
[ERROR] Failed to execute goal io.gatling:gatling-maven-plugin:2.2.0:execute (default-cli) on project uhs-wrapper-performance: Gatling failed. java.lang.ClassNotFoundException: simulations.UhsWrapperSimulation$$anonfun$initSession$1$$anonfun$1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.gatling:gatling-maven-plugin:2.2.0:execute (default-cli) on project uhs-wrapper-performance: Gatling failed.
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoE …
```
=> Fix test classpath escaping issue

pom.xml, src/main/java/io/gatling/mojo/AssertionsSummary.java, src/main/java/io/gatling/mojo/VerifyMojo.java, src/test/java/io/gatling/mojo/AssertionsSummaryTest.java, src/test/resources/golden-files/assertions.xml
This PR addresses https://github.com/gatling/gatling/issues/3379 by adding a new `VerifyMojo` for a _verify_ goal that binds to the _verify_ lifecycle phase. It scans the output folder for _assertions.xml_ files and fails the build if one of them contains errors or failures.
In order to use this feature, `failOnError` has to be set to false so that the _verify_ phase is reached.
The code was inspired by 
https://github.com/gatling/gatling-maven-plugin/blob/3b01b84e52afc102d3fba7928c1f20349487edce/src/main/java/io/gatling/mojo/GatlingMojo.java#L290-L311
and
https://github.com/apache/maven-surefire/blob/a69f10f61f53139f93dc69f19f8df18c6ba9c94c/maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/util/FailsafeSummaryXmlUtils.java#L76-L97
Example configuration:
```xml
<plugin> …
```
=> Add a verify goal that detects failed simulations

src/main/java/io/gatling/mojo/AbstractGatlingExecutionMojo.java, src/main/java/io/gatling/mojo/GatlingMojo.java, src/main/java/io/gatling/mojo/VerifyMojo.java
The `VerifyMojo` does not respect the `gatling.skip` property.
This can lead to unexpected behavior.
To reproduce,
1. Create a simulation with failing assertions.
2. Configure *gatling-maven-plugin* like this
```xml
<executions>
<execution>
<goals>
<goal>test</goal>
<goal>verify</goal>
</goals>
</execution>
</executions>
<configuration>
<failOnError>false</failOnError>
</configuration>
```
3. Run `mvn clean verify`.
Verification will fail, which is expected.
4. Run `mvn verify -Dgatling.skip`.
Expected behavior: both Gatling execution and verification are skipped.
Actual behavior: Verification error due to the recorded failures of the previous run.
With this PR, verification will be skipped as expected.
I extracted a new superclass in order to remove duplicated declaration of properties …
=> Make VerifyMojo honor the gatling.skip property

src/main/java/io/gatling/mojo/Fork.java, src/main/java/io/gatling/mojo/GatlingMojo.java
Same idea as e.g. failsafe plugin: http://maven.apache.org/surefire/maven-failsafe-plugin/integration-test-mojo.html#workingDirectory
This improves support for Maven multi-module projects as the plugin can be run within a sub-module underneath some parent.
=> Add support for setting workingDirectory 

.github/workflows/ci.yml
Motivation:
Github action failed
Modifications:
Use `--no-run-if-empty` option for `xarg`
Result:
Github action succeed
=> Call rm only if operands exist

pom.xml, src/main/java/io/gatling/mojo/EnterpriseDeployMojo.java, src/main/resources/META-INF/plexus/components.xml
**Motivation:**
Upload artifact from maven plugin on Gatling Enterprise
**Modification:**
* Use `gatling-enterprise-plugin-commons` enterprise client to upload
* Add `enterprisePackage` goal to upload package
**Result:**
Upload using `deploy` with extensions, or `gatling:enterpriseDeploy`.
Need configuration of `packageId` or `apiToken`.
=> Gatling Enterprise upload package, closes MISC-229

.github/workflows/ci.yml, README.adoc, pom.xml, src/main/java/io/gatling/mojo/DeprecatedFrontLineMojo.java, src/main/java/io/gatling/mojo/EnterpriseDeployMojo.java, src/main/java/io/gatling/mojo/EnterprisePackageMojo.java, src/main/java/io/gatling/mojo/EnterpriseUtil.java, src/main/java/io/gatling/mojo/GatlingMojo.java, src/main/resources/META-INF/plexus/components.xml
**Motivation:**
No need to configure frontline-maven-plugin to package a Jar for gatling
enterprise.
**Modification:**
* Add `gatling:enterprisePackage` goal, packaging shaded Jar
* Support deprecated `package` goal for compatibility
* Add warning when `frontline-maven-plugin` is configured
* Remove `maven-jar-plugin` dependency
**Result:**
Shaded Jar created using either `mvn gatling:enterprisePackage` or
deprecated package phase binding.
---
**Motivation:**
Use standard maven phase with gatling maven plugin
**Modification:**
Add gatling component phases configuration
**Result:**
By using gatling packaging:
* `integration-test` binded to `gatling:test`
* `package` binded to `gatling:enterprisePackage`
---
=> Merge Gatling Enterprise packaging, closes MISC-223

src/main/java/io/gatling/mojo/GatlingMojo.java
fixes https://github.com/gatling/gatling/issues/4165
=> Don't require io.gatling.javaapi.core.Simulation to be on the classpath

.mvn/jgitver.config.xml
Motivation:
Cannot mvn install twice in a row.
Difficult to test the development
Modifications:
Add a configuration
Result:
better work
=> fix: use SNAPSHOT version when not in tags

src/etc/header.txt, src/main/java/io/gatling/mojo/AbstractGatlingExecutionMojo.java, src/main/java/io/gatling/mojo/AbstractGatlingMojo.java, src/main/java/io/gatling/mojo/AssertionsSummary.java, src/main/java/io/gatling/mojo/CompilationException.java, src/main/java/io/gatling/mojo/DeprecatedFrontLineMojo.java, src/main/java/io/gatling/mojo/EnterprisePackageMojo.java, src/main/java/io/gatling/mojo/EnterpriseUploadMojo.java, src/main/java/io/gatling/mojo/EnterpriseUtil.java, src/main/java/io/gatling/mojo/Fork.java, src/main/java/io/gatling/mojo/GatlingMojo.java, src/main/java/io/gatling/mojo/GatlingSimulationAssertionsFailedException.java, src/main/java/io/gatling/mojo/MainWithArgsInFile.java, src/main/java/io/gatling/mojo/MojoConstants.java, src/main/java/io/gatling/mojo/MojoUtils.java, src/main/java/io/gatling/mojo/RecorderMojo.java, src/main/java/io/gatling/mojo/VerifyMojo.java, src/test/java/io/gatling/mojo/AssertionsSummaryTest.java, src/test/java/io/gatling/mojo/VerifyMojoTest.java
Alternatively, we could use `2011-$YEAR` and also configure `ratchetFrom` (something like `<ratchetFrom>origin/main</ratchetFrom>`); but that would only update the year on files actually modified (different from what we have in our SBT builds).
=> chore: Update copyright year 2022

.mvn/jgitver.config.xml
Motivation:
Last release was difficult because CI tried to compute the version from the tag
but always append -SNAPSHOT qualifier (because of bad configuration.
Modifications:
* Remove useSnapshot configuration (that was the mistake)
* Configure the MAVEN strategy
Result:
jgitver plugin bumps as patch and append SNAPSHOT qualifier when not directly on tag
=> fix: use SNAPSHOT qualifier only for no tag commit

pom.xml, src/main/java/io/gatling/mojo/AbstractEnterprisePluginMojo.java, src/main/java/io/gatling/mojo/EnterpriseStartMojo.java, src/main/java/io/gatling/mojo/EnterpriseUploadMojo.java
Motivation:
gatling-enterprise-plugin-common now look for simulation classes.
Modifications:
* Delegate simulations discovery to commons library
* Handle introduced exceptions
* Take advantage of common interface between batch and interactive
enterprise plugin
Result:
If there is no simulation classes, error is returned during plugin execution instead of on cloud.
Ref: MISC-355
=>  feat: delegate simulation class discovery to common package MISC-355

pom.xml, src/main/java/io/gatling/mojo/EnterpriseStartMojo.java, src/main/java/io/gatling/mojo/EnterpriseUploadMojo.java, src/main/java/io/gatling/mojo/RecoverEnterprisePluginException.java
chore: centralize plugin exception handling accross tasks
---
**Motivation:**
Recovering from error is always the same
**Modification:**
Add RecoverEnterprisePluginException to extend in order to get recovering method
feat: handle unsupported version exception, closes MISC-373
---
**Motivation:**
New commons version throw `UnsupportedJavaVersionException` when java version isn't supported by Gatling Enterprise CLoud
**Modification:**
Log exception message, along java option to target a compatible bytecode.
fix: log simulation creation on enterprise start exception
---
**Motivation:**
On start, exception may occured after simulation creation.
**Modification:**
Log simulation creation if creation flag is true in exception.
=> feat: handle unsupported version exception, closes MISC-373

src/main/java/io/gatling/mojo/EnterpriseStartMojo.java
Motivation:
- it was impossible to configure system properties in the command line
Modification:
- use new version of the commons client
- add support for system properties as string
result:
- user can now pass the system properties as a formatted string
=> feat: Add support for system properties as string, see MISC-388

pom.xml, src/main/java/io/gatling/mojo/EnterpriseStartMojo.java
Motivation:
- we can send env variables with the new version of commons
Modifications:
- updated  code to new vesion of commons
- send env variables when starting a simulation on gatling cloud
- simulationEnvironmentVariablesString or simulationEnvironmentVariables can be used
=> Pass env variables when starting simulation on gatling cloud, see MISC-368

pom.xml, src/main/java/io/gatling/mojo/AbstractEnterprisePluginMojo.java, src/main/java/io/gatling/mojo/EnterpriseStartMojo.java, src/main/java/io/gatling/mojo/EnterpriseUploadMojo.java
Motivation:
Remove OkHttpClient where older version contain CVEs
Modifications:
* upgrade gatling-enteprise-plugin-commons to 1.3.0
Result:
Less dependencies to OkHttp
=> chore: upgrade gatling-enteprise-plugin-commons to 1.3.0

.github/workflows/ci.yml, .github/workflows/release.yml, pom.xml
Motivation:
Signature prerequisites are not always available (and should not)
CI (for PR) failed because maven cannot sign without gpg keys (and was right)
Modifications:
* Move sign plugin configuration into a profile that is only activated in the release GITHUB_JOB (where we provide gpg keys)
Result:
CI pass, developers can call mvn verify, signature gpg keys are only used when required
=> [WIP] chore: move sign plugin configuration into profile

src/main/java/io/gatling/mojo/EnterpriseStartMojo.java, src/main/java/io/gatling/mojo/RecoverEnterprisePluginException.java
ref: MISC-395
Motivation:
When running enterpriseStart with a specified simulation, the error handler which handles standard errors from the common client is bypassed. This is notably seen for UnsupportedJavaVersionException. 
Modifications:
- Use the RecoverEnterprisePluginException handler regardless of whether we start an existing simulation or create a new one.
- Improve the error message in case of UnsupportedJavaVersionException.
Result:
Better information for the user in case of error.
=> Fix error handling for enterpriseStart with existing simulation, notably Java version errors

src/main/java/io/gatling/mojo/RecorderMojo.java
Motivation:
When running the recorder from the plugin, the simulationsFolder currently always defaults to the standard Java test sources root (even in a project set up for Kotlin or Scala).
Modifications:
Use the first element in project.testCompileSourceRoots as the default simulationsFolder.
Result:
The recorder will default to saving simulations to the folder set with <testSourceDirectory> in the POM, which is typically what the user would expect.
=> Improve default simulationsFolder for the Recorder

pom.xml, src/main/java/io/gatling/mojo/AbstractEnterprisePluginMojo.java, src/main/java/io/gatling/mojo/EnterpriseStartMojo.java
Usage exemples:
- Default behavior doesn't change: fire and forget, only guarantees that the run was started with the API, we don't wait for any specific status or result.
- We can add `<waitForRunEnd>true</waitForRunEnd>` or run with e.g. `mvn gatling:enterpriseStart -Dgatling.enterprise.waitForRunEnd=true`.
=> Add ability to monitor progress and wait for run end for enterpriseStart

src/main/java/io/gatling/mojo/AbstractEnterprisePluginMojo.java
Motivation:
Our users doesn't know about private or public control plane.
Modifications:
Remove private prefix on configuration.
=> chore: remove "private" prefix from control plane config

src/main/java/io/gatling/mojo/EnterprisePackageMojo.java, src/main/java/io/gatling/mojo/MojoConstants.java, src/main/java/io/gatling/mojo/MojoUtils.java
Motivation:
Instead of having to remove transitive dependencies from new modules by (group id, artifact id) manually (e.g.: Gatling gRPC), it is simpler to get the dependencies of all the submodules of the known group ids instead.
=> feat: get transitive dependencies by group id instead of limiting to artifact id

src/main/java/io/gatling/mojo/GatlingMojo.java
Motivation:
Useless option, resources are picked from the classpath or absolute path.
=> chore: drop resourcesFolder option

src/main/java/io/gatling/mojo/AbstractGatlingMojo.java, src/main/java/io/gatling/mojo/EnterpriseStartMojo.java, src/main/java/io/gatling/mojo/GatlingMojo.java, src/main/java/io/gatling/mojo/Interactive.java, src/main/java/io/gatling/mojo/MojoUtils.java
Motivation:
The interactive mode of the old bundle was very helpful.
We should replicate it in the maven plugin now that it's replacing the old bundle.
Modification:
Unless maven batch mode is enable or the CI env var is set to true, switch to interactive mode and let the user select the simulation class and the run description.
Interactive mode will be completely dropped from core Gatling.
=> feat: switch interactive mode based on maven --batch-mode option or CI env var

pom.xml, src/main/java/io/gatling/mojo/EnterpriseDeployMojo.java
Motivation:
Support new deployment file to create package and simulation
Modifications:
Add enterpriseDeploy target that call deploy utilities in gatling-plugin-commons
=> feat: add enterpriseDeploy target, closes HYB-514

src/main/java/io/gatling/mojo/EnterpriseUploadMojo.java
Motivation:
- Package Descriptor feature is going out of beta and v1 is coming
Modifications:
- Remove beta package descriptor deployment call from enterpriseUpload target
Result:
- Beta package descriptor: out
=> chore: drop beta package descriptor feature, closes HYB-544

pom.xml, src/main/java/io/gatling/mojo/AbstractEnterprisePluginMojo.java, src/main/java/io/gatling/mojo/AbstractGatlingMojo.java, src/main/java/io/gatling/mojo/CommonLogMessage.java, src/main/java/io/gatling/mojo/EnterpriseDeployMojo.java, src/main/java/io/gatling/mojo/EnterpriseStartMojo.java, src/main/java/io/gatling/mojo/GatlingMojo.java, src/main/java/io/gatling/mojo/RecoverEnterprisePluginException.java, src/main/java/io/gatling/mojo/UnsupportedClientMojoException.java
Do not merge until @tpetillot release an M16 milestone :)
Motivation:
Interactive & CI envvar detection should be shared in common plugin library.
Modifications:
- Upgraded to 1.9.0-M16
- Deleted interactive() method
- Pull-up buildTool field, requireBatchMode, pluginConfiguration.
Result:
Less logic in maven plugin, more in common !
=> chore: upgrade to 1.9.0-M17

src/main/java/io/gatling/mojo/GatlingMojo.java
Ref: 733590657b96084d6b74294144ffab53c59a2cff
=> chore: keep compatility for gatling version < 3.11

pom.xml, src/main/java/io/gatling/mojo/EnterpriseDeployMojo.java, src/main/java/io/gatling/mojo/EnterpriseUploadMojo.java
[chore: drop enterprise upload command with expressive message](https://github.com/gatling/gatling-maven-plugin/commit/976721d8f245ad38bffb6d276587d6be46d515e7)
**Motivation:**
Command is replaced by enterprise deploy.
**Modification:**
Drop command support, when command is called an error message redirect to deploy command documentation.
[chore: handle simulation validation ID on deploy command](https://github.com/gatling/gatling-maven-plugin/commit/83739626bc163d67c39233bfdf59ad6f81ff1934)
**Motivation:**
Validate a given simulation ID have been deployed.
=> chore: handle simulation validation ID on deploy command
